INCLUDE "engine/surfing_minigame.asm"
INCLUDE "engine/yellow_intro.asm"
INCLUDE "data/animated_objects_3e_2.asm"
YellowIntroGraphics1: INCBIN "gfx/yellow_intro1.2bpp"
YellowIntroGraphics2: INCBIN "gfx/yellow_intro2.2bpp"
INCLUDE "engine/animated_objects_3e.asm"
